robot:
  name: "OptimusRepo"
  ip_address: "192.168.0.15"
  rigid_body_id: 1

topics:
  state: "robot_state" # topic name

motion_capture_system: "optitrack" # Options: "optitrack"
update_rate: 10 # Hz

network:
  optitrack:
    server_address: "192.168.0.3" # server IP running optitrack
    multicast_address: "239.255.42.99" # Default OptiTrack multicast IP
    command_port: 1510
    data_port: 1511
